### ISSUE TITLE
Doesn't work with the latest PyPump

### ISSUE THREAD

**Issue by strugee** [dper/pumptweet#21]
Seems like PyPump has made some breaking API changes. For example, `pump.get_registration()` and `pump.get_token()` (as mentioned in the README) don't exist anymore.

**Comment by dper** [comment]
As of https://github.com/dper/pumptweet/commit/a4f06f81e3fe34e40ccb059d01a06c2b9106ec10, this should be working with the current version from source.

I have not yet updated PyPI but plan on doing so soon.

**Comment by strugee** [comment]
Wow, this was really fast, thanks!

And I was just getting ready to finish up my PR :)
