### ISSUE TITLE
< characters are gratuitously removed

### ISSUE THREAD

**Issue by strugee** [dper/pumptweet#25]
This is unfortunate if, like me, you like to type ASCII hearts.

<3

**Comment by dper** [comment]
My original line of thinking was to remove HTML in the cross-posting, since its functionality could not be guaranteed on Twitter. Of course, your ASCII heart is not HTML and therefore it should not be modified. It would seem the HTML-stripping code is doing too much.

**Comment by strugee** [comment]
Just as I thought! :)

Thanks for your hard work oin this project, by the way.

**Comment by dper** [comment]
This is happening in `MLStripper.py`.

```
s = MLStripper()
s.feed(html)
```
I would have expected the stripper to remove HTML tags.  It's removing angle brackets, too.

@strugee My pleasure.

**Comment by dper** [comment]
Let me know if this doesn't fix it. :-)
