### ISSUE TITLE
Vague error when pump server down

### ISSUE THREAD

**Issue by dper** [dper/pumptweet#26]
Right now, `microca.st` is down. When I run `pumptweet.py`, here's the error I get. It should be more informative.

```
$ ./pt.py
Reading the config file...
Logging into the Pump server...
Logging into Twitter...
Looking at Pump outbox activity...
Traceback (most recent call last):
  File "./pt.py", line 18, in <module>
    pumptweet.pull_and_push()
  File "/home/d/src/pumptweet/pumptweet/PumpTweet.py", line 156, in pull_and_push
    notes = self.get_new_activities()
  File "/home/d/src/pumptweet/pumptweet/PumpTweet.py", line 42, in get_new_activities
    outbox = self.pump_me.outbox
  File "/home/d/src/pumptweet/local/lib/python2.7/site-packages/pypump/models/person.py", line 67, in outbox
    self._outbox = self._outbox or Outbox(self.links['activity-outbox'], pypump=self._pump)
KeyError: 'activity-outbox'
```

Originally posted at https://github.com/xray7224/PyPump/issues/138. Thanks, @strugee!

**Comment by dper** [comment]
Confirm that the error is gone now that `microca.st` is up.

**Comment by dper** [comment]
Added better handling of servers where the domain can't be resolved in https://github.com/dper/pumptweet/commit/dce8c28902c578abddd2fc5625fd4a38be5dc803.

This does not address the above error where the machine was reachable by `ping` but the server was unresponsive.

**Comment by dper** [comment]
Added code to handle the situation where a machine is responsive but doesn't appear to be running a pump server in https://github.com/dper/pumptweet/commit/378f755bbaa7b95c1dd14128ef333a6b6523d942.

**Comment by dper** [comment]
With `microca.st` the other day, it was neither entirely up nor entirely down.  I don't know how to reproduce that kind of situation in order to test for it.  And even if I could, there are so many ways a server could be online but malfunctioning that it seems like something not to deal with.

To recap, we now properly handle domains that don't resolve and domains that resolve but don't have pump running.  We do not handle cases where pump is sort of running but sort of broken.

**Comment by mrvdb** [comment]
Just a FYI, if the oauth process fails to complete but there are still credentials in `~/.config/PyPump` the same error occurs. 
Took me a bit to figure this out (server was fine, all clients working etc.)

**Comment by dper** [comment]
@mrvdb Thank you for letting us know. (And for using PumpTweet. :-)) For errors of this type, it's difficult to write code that can identify and handle them all well. On the other hand, I could easily add a section to the documentation, if that would be sensible. What do you think?

**Comment by mrvdb** [comment]
Adding a section to the documentation would be good in any case. I haven't looked in detail at the code yet, because I was also juggling a pyPump bug at the time, which may have been the culprit for this /side-effect/  That is, writing out credentials info while it should not have.
