### ISSUE TITLE
Add support for 'Picture' type posts.

### ISSUE THREAD

**Issue by mrvdb** [dper/pumptweet#32]
It would be nice if there was support for the 'picture type' post, like in the pump.io web client.

**Comment by mrvdb** [comment]
I saw the function as well and it seemed 'doable'. I just wanted to register an issue which I could follow and perhaps work on it when time permits.

**Comment by dper** [comment]
Relevant python-twitter documentation: <https://python-twitter.readthedocs.io/en/latest/twitter.html#twitter.api.Api.PostMedia>

There are several ways of posting media using python-twitter. I think the most appropriate involves passing it the URL of the target image.

**Comment by mrvdb** [comment]
I think we may want to use https://python-twitter.readthedocs.io/en/latest/twitter.html?highlight=postupdate#twitter.api.Api.PostUpdate as the reference. The PostMedia method is deprecated.

**Comment by dper** [comment]
@mrvdb Yes. :+1:

**Comment by dper** [comment]
Code for cross-posting notes is partly done in <https://github.com/dper/pumptweet/commit/ab03674a1377dec1d20f57594a2789c65855e8da>. It is commented out right now.

It uses `PostUpdate` as recommended above.

I don't know how to find the URL of the image itself on the  Pump server. This should look something like `https://urmf.net/uploads/pumptweet/2016/7/6/gwCWMg.png`. Has anyone gotten this information using PyPump before?

To experiment with it, see [these](https://github.com/dper/pumptweet/blob/ab03674a1377dec1d20f57594a2789c65855e8da/pumptweet/PumpTweet.py#L72) [two](https://github.com/dper/pumptweet/blob/ab03674a1377dec1d20f57594a2789c65855e8da/pumptweet/PumpTweet.py#L151) sections.

For testing, I hard-coded an image URL and the post successfully cross-posted.

**Comment by dper** [comment]
[JanKusanagi@identi.ca](https://identi.ca/jankusanagi) commented:
> I imagine the source code of NavierStokes might help =)

[kabniel@microca.st](https://microca.st/kabniel) commented:
> It should be stored in yourimage.original.url (and yourimage.thumbnail.url for the thumbnail url)
> See https://pypump.readthedocs.io/en/late... for more information

**Comment by mrvdb** [comment]
Here's a snippet from PumpTools.py from NavierStokes:

``` python
   if isinstance( pump_obj, Image):
                img_url = pump_obj.original.url

                message.link = img_url

                # construct a request to grab the image
                endpoint = "{0}".format('/'.join(img_url.split('/')[3:]))
                # remove "_thumb" from the image name to get the original image
                endpoint = endpoint.replace('_thumb','')
                local_img_name = endpoint.split('/')[-1]
```

**Comment by dper** [comment]
For me, `obj.original = None`. This is inauspicious. :-/ Does anyone know why?

Good news, though. `obj.thumbnail.url` has a URL to either the original image (if it is small) or to a reduced-size version of it (if it is large). That URL ends in `_thumb.suffix` in the latter case.  Here are two URLs showing what it looks like.

```
https://urmf.net/uploads/pumptweet/2016/7/6/gwCWMg.png
https://urmf.net/uploads/pumptweet/2016/7/6/gwCWMg_thumb.png
```

How about we follow [NavierStokes](https://hub.polari.us/code/index.cgi/navierstokes/tree/PumpTools.py?h=v1.0.X&id=a8460e8f5098849247d188ddc18db90234d12601#n184)'s lead and use that URL, removing `_thumb` as necessary?

**Comment by mrvdb** [comment]
@dper original is always `None` for Image type objects? that sounds odd.

I'm game for any working solution, it's not like we can't improve later on

**Comment by dper** [comment]
Done in <https://github.com/dper/pumptweet/commit/ed3f633ba2533c88458151c3c089f4e2dfdd11ca>. I've tested it with several large and small images. All successful.

As an aside, `PostUpdates` didn't work (why?). `PostUpdate` is used here. `PostMedia` works but is deprecated.

**Comment by mrvdb** [comment]
This does not work for me (and I expect for others)

The URL for uploads requires me to have the proper cookie (i.e. be logged in). The strange thing is that microca.st (which I think you use?) does not have that requirement, so it would work there.

**Comment by mrvdb** [comment]
This turned out to be an issue in pump.io itself, commit https://github.com/e14n/pump.io/commit/0c9053174850142ffe5bf8679b18c2e53f63b12d caused the trouble.  All is well now. :-)

**Comment by mrvdb** [comment]
Issue for reference: https://github.com/e14n/pump.io/issues/1174

**Comment by dper** [comment]
The problem where we're forced to use thumbnails is fixed in PyPump master. When PyPump 0.7 comes out, we can replace those lines with just one. :-)
