### ISSUE TITLE
DeprecationWarning: The value of convert_charrefs will become True in 3.5

### ISSUE THREAD

**Issue by strugee** [dper/pumptweet#34]
I've been getting occasional emails from cron with the text:

    /home/alex/pumptweet/pumptweet/MLStripper.py:10: DeprecationWarning: The value of convert_charrefs will become True in 3.5. You are encouraged to set the value explicitly.
      super().__init__()

Weirdly, this only seems to happen occasionally.

I'm on 6b14c9bd6f9a3e251049d8a79a6c7ac05cca836b. virtualenv is using Python 3.4.2, and I'm on a Debian Jessie system.

**Comment by dper** [comment]
On 3.5, which I use, the default value is already True and I haven't seen that error. Regardless, the obvious fix is to add `convert_charrefs=True` to `MLStripper.py`. Done: <https://github.com/dper/pumptweet/commit/a158728cacf5df8f49dc679e0e15b26bf1247efc>.

The argument itself has to do with HTML entities, but such entities are handled prior to the point where this warning shows up. As best I can tell, setting the argument shouldn't impact functionality.

@strugee If you would like to try this and see what happens, that'd be great. :-)

**Comment by strugee** [comment]
@dper closing since I haven't seen emails for a couple days - will reopen if it reappears :)
